### ISSUE TITLE
Add option to change dropdown icon

### ISSUE THREAD

**Issue by tomaz-dugii** [yudiz-solutions/CountryCodePickerPlus#5]
Is it possible to implement functionality to change dropdown icon to not be always `Icons.arrow_drop_down` but something custom. So we can also use this icon `Icons.expand_more` For example something like this ?
![Screenshot 2024-10-03 at 10 50 34](https://github.com/user-attachments/assets/19732b09-b8d5-4417-83b3-5bb45f034dd7)

**Comment by YudizAndroidNareshP** [comment]
The issue with the dropdown icon in [country_code_picker_plus: ^0.0.9](https://pub.dev/packages/country_code_picker_plus) has been fixed. 
![Screenshot 2024-10-04 at 10 45 40 AM](https://github.com/user-attachments/assets/55b0f719-a38d-4bcd-a9bb-7a85be45eee1)

**Comment by tomaz-dugii** [comment]
Awesome. Thank you for that.
